server:
  port: 80
spring:
  application:
    name: cloud-order-service
  cloud:
    consul:
      host: 192.168.0.208
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-url: http://192.168.1.145:80/actuator/health